@startuml

' các class Application và Initializable của java có sẵn liệu có phải vẽ vào k

skinparam ClassAttributeIconSize 0

package application <<Folder>> {
    class Main {
        +start(Stage primaryStage): void
        +{static}main(String[] args): void
    }
    package Main.fxml <<Frame>> {
    }
    class SceneController {
        -myCanvas: AnchorPane
        -DFSParam: TextField
        -from: TextField
        -to: TextField
        -nextStepButton: Button
        -noteText: Label
        -resText: Label
        -createUGraph: Button
        -createDGraph: Button
        -removeE: Button
        -DFSButton: Button
        -RunC: Button
        -RunT: Button
        -pseudoBox: VBox
        -GenDGraph: Button
        -GenUGraph: Button
        -context: Context
        -lines: List<Label>
        -mode: int
        -graph: Graph
        -listEdge: HashMap<Pair<Integer, Integer>, Edge>
        +initialize(arg0: URL, arg1: ResourceBundle ): void
        +generateUndirectedGraph(): void
        +generateDirectedGraph(): void
        +handleMouseOnCanvas(e: MouseEvent): void
        -getVertex(e: MouseEvent): Vertex
        +runDFS(): void
        +runNextStep(): void
        +createNewGraph(): void
        +createNewDirectedGraph(): void
        +runTopo(): void
        +removeEdge(): void
        +runCutVertex(): void
        +reset(): void
        +resetColor(): void
    }
}

Main - Main.fxml
Main.fxml - SceneController

@enduml
