@startuml

package algorithmcontext <<Folder>> {
    class Context{
        -alg: Algorithm
        +setAlgorithm(alg: Algorithm): void
        +play(): void
        +getAlgorithm(): Algorithm
    }
}

@enduml
